spring.application.name=KS_IMS_Batch
# DataBase
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:postgresql://192.168.50.52:5432/ksims
spring.datasource.username=postgres
spring.datasource.password=postgres
# Log Settings
logging.level.root=info 
logging.level.com.ksinfo=debug 
# Mapper
mybatis.config-location=classpath:config/mybatis_config.xml
mybatis.mapper-locations=classpath:mapper/*.xml

#Batch Setting
spring.batch.initialize-schema=always
spring.batch.job.names=${job.name:NONE}
