#SendEmail
expiration.sender=System
expiration.subject=様、在留カード有効期限のお知らせ
expiration.content=様、在留カード有効期限のお知らせ

monthlyCheck.sender=System
monthlyCheck.subject=月次確認事項及び勤務表未登録の件

regularPassCheck.sender=System
regularPassCheck.subject=交通費未登録の件

send.host=smtp.ks-infosys.com
send.username=hitobito@ks-infosys.com
send.password=hitobitO1114