#SendEmail
SENDER_ADDRESS=soumu@ks-infosys.com
BATCH_TARGET_ADMIN=soumu@ks-infosys.com

expiration.sender=System
expiration.subject=【自動通知】在留カード（在留期間）更新時期のご案内
expiration.content= 様、\n\nいつもお世話になっております。\nKS情報システム株式会社 管理本部です。\n\n本メールは自動送信にてお送りしております。\n\nご登録いただいている在留カードにつきまして、\n在留期間の更新時期が近づいておりますのでご案内いたします。\n\n在留期間の更新手続きは、\n在留期限の3か月前より申請可能となっております。\nお早めにご準備のうえ、お手続きをお願いいたします。\n\n在留期間更新に必要な書類につきましては、\n管理本部より別途ご案内いたしますので、\n今しばらくお待ちください。\n\nご不明な点等がございましたら、お気軽にご連絡ください。\n何卒よろしくお願いいたします。

monthlyCheck.sender=System
monthlyCheck.subject=月次確認事項及び勤務表未登録の件

regularPassCheck.sender=System
regularPassCheck.subject=交通費未登録の件

send.host=smtp.ks-infosys.com
send.username=hitobito@ks-infosys.com
send.password=hitobitO1114