#SendEmail
SENDER_ADDRESS=soumu@ks-infosys.com
BATCH_TARGET_ADMIN=soumu@ks-infosys.com

test.sender=System
test.subject= デプロイテスト用メール
test.content= デプロイテスト完了

expiration.sender=System
expiration.subject=【自動通知】在留カード（在留期間）更新時期のご案内
expiration.content= 様、\n\nいつもお世話になっております。\nKS情報システム株式会社 管理本部です。\n\n本メールは自動送信にてお送りしております。\n\nご登録いただいている在留カードにつきまして、\n在留期間の更新時期が近づいておりますのでご案内いたします。\n\n在留期間の更新手続きは、\n在留期限の3か月前より申請可能となっております。\nお早めにご準備のうえ、お手続きをお願いいたします。\n\n在留期間更新に必要な書類につきましては、\n管理本部より別途ご案内いたしますので、\n今しばらくお待ちください。\n\nご不明な点等がございましたら、お気軽にご連絡ください。\n何卒よろしくお願いいたします。
expiration.slackEmail= ksinfosys.dzhi3b@zapiermail.com

conductCheck.sender=System
conductCheck.subject=【自動通知】勤務表未登録のご連絡
conductCheck.content=様、\n\nいつもお世話になっております。\nKS情報システム株式会社 管理本部です。\n\n本メールは自動送信にてお送りしております。\n\n月初2日が経過した時点で、\n当月分の勤務表が未登録となっている方へ\nご連絡を差し上げております。\n\nお手数ですが、\n社内システムより速やかに勤務表のご登録をお願いいたします。\n\nご不明な点がございましたら、\n管理本部までお問い合わせください。
conductCheck.admincontent=いつもお世話になっております。\n勤務表の未登録のお知らせです。\n\n下記の方は勤務表の登録が必要です。\n$name$\n
conductCheck.slackEmail= ksinfosys.dzhi3b@zapiermail.com

monthlyCheck.sender=System
monthlyCheck.subject=月次確認事項及び勤務表未登録の件

regularPassCheck.sender=System
regularPassCheck.subject=【自動通知】交通費未登録のご連絡
regularPassCheck.content=様、\n\nいつもお世話になっております。\nKS情報システム株式会社 管理本部です。\n\n本メールは自動送信にてお送りしております。\n\n月初5営業日が経過した時点で、\n交通費の申請・登録が確認できておりませんので、\nご案内いたします。\n\n該当する方は、\n社内システムより交通費の登録をお願いいたします。\n\nご不明な点がございましたら、\n管理本部までお問い合わせください。
regularPassCheck.admincontent=いつもお世話になっております。\n交通費の未申請及び未登録のお知らせです。\n\n下記の方は、社内システムより交通費の登録をお願いいたします。\n$name$\nご不明な点がございましたら、\n管理本部までお問い合わせください。
regularPassCheck.slackEmail= ksinfosys.dzhi3b@zapiermail.com

timeSheetCheck.sender=System
timeSheetCheck.subject=【自動通知】勤務表未登録のご連絡
timeSheetCheck.content=様、\n\nいつもお世話になっております。\nKS情報システム株式会社 管理本部です。\n\n本メールは自動送信にてお送りしております。\n\n月初5営業日が経過した時点で、\n当月分の勤務表が未登録となっている方へ\nご連絡を差し上げております。\n\nお手数ですが、\n社内システムより速やかに勤務表のご登録をお願いいたします。\n\nご不明な点がございましたら、\n管理本部までお問い合わせください。

send.host=smtp.ks-infosys.com
send.username=ks-notice@ks-infosys.com
send.password=Notice2026